import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
const source=(await fs.readFile('src/services/registration.js','utf8')).replace("import { config } from '../config';", "const config={appsScriptUrl:'https://script.google.com/macros/s/test/exec'};");
const {submitRegistration}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const data={prenom:'Alpha',nom:'Test',email:'test@example.com',age:'17',telephone:'+212 600000000',contact_parent:'+212 611111111',etablissement:'School',niveau:'Grade',ville:'City',pack:'500',participations_mun:'0',experience_details:'No previous MUN experience',motivation:'Learn in my chosen committee',attentes:'Learn',logistique:'None',comite_choix_1:'INTERPOL',comite_choix_2:'UE',comite_choix_3:'MPS',confirmation_pack:'on',code_conduite:'on',exactitude:'on',consentement:'on'};
for(const [label,response,code] of [['success',()=>Response.json({ok:true}),null],['refused',()=>Response.json({ok:false}),'SCRIPT_REJECTED'],['unconfirmed',()=>Response.json({}),'UNCONFIRMED_JSON'],['HTML',()=>new Response('<html>'),'INVALID_JSON'],['HTTP',()=>new Response('',{status:502}),'HTTP_ERROR'],['network',()=>{throw new TypeError();},'RESPONSE_INACCESSIBLE'],['opaque',()=>({type:'opaque',headers:new Headers()}),'RESPONSE_INACCESSIBLE']])test('client '+label,async()=>{const original=globalThis.fetch;let calls=0;globalThis.fetch=async(url,options)=>{calls++;assert.equal(url,'/api/registration');assert.equal(options.mode,undefined);assert.equal(options.body.get('age'),'17');assert.equal(options.body.get('code_conduite'),'on');return response();};try{if(code)await assert.rejects(submitRegistration(data),e=>e.code===code);else await submitRegistration(data);assert.equal(calls,1);}finally{globalThis.fetch=original;}});
const script=await fs.readFile('integration/Code.gs','utf8');
function setup(){let table=[['Date','Nom','Pack DH','Motivation'],['old','Previous','550','old motivation']];let releases=0;
 const sheet={getLastColumn:()=>table[0].length,getLastRow:()=>table.length,getMaxColumns:()=>100,getMaxRows:()=>100,moveColumns(range,dest){const index=range.col-1;for(const row of table){const [value]=row.splice(index,1);row.splice(dest-2,0,value);}},getRange(row,col,height,width){return {col,getValues:()=>[table[0].slice(col-1,col-1+width)],setValue(value){table[0][col-1]=value;},setValues(values){table[row-1]=values[0];},setNumberFormat(){}};}};
 const context=vm.createContext({Utilities:{getUuid:()=> 'test'},LockService:{getScriptLock:()=>({waitLock(){},releaseLock(){releases++;}})},PropertiesService:{getScriptProperties:()=>({getProperty:()=> 'sheet'})},SpreadsheetApp:{openById:()=>({getSheetByName:()=>sheet}),flush(){}},ContentService:{MimeType:{JSON:'json'},createTextOutput:text=>({setMimeType:()=>JSON.parse(text)})},console:{info(){},error(){},log(){}}});vm.runInContext(script,context);return {context,table,releases:()=>releases};}
function post(state,changes={}){return state.context.doPost({parameter:{...data,type:'registration',...changes}});}
test('migration preserves historic prices and motivation, maps fields by header',()=>{const s=setup();assert.equal(post(s).ok,true);assert.equal(s.table[0].at(-1),'Motivation');assert.equal(s.table[1][s.table[0].indexOf('Pack DH')],'550');assert.equal(s.table[1].at(-1),'old motivation');assert.equal(s.table[2][s.table[0].indexOf('Âge')],'17');assert.equal(s.table[2][s.table[0].indexOf('Téléphone')],"'+212 600000000");assert.equal(s.table.length,3);assert.equal(s.releases(),1);});
for(const changes of [{pack:'550'},{pack:'1550'},{age:'0'},{age:'17.5'},{contact_parent:''},{telephone:'abc'},{email:'bad'},{code_conduite:'false'},{exactitude:''},{confirmation_pack:'true'},{participations_mun:'-1'},{participations_mun:'1.5'},{participations_mun:''},{experience_details:''},{motivation:''},{attentes:''},{logistique:''},{consentement:'false'},{comite_choix_1:'Invented'}])test('server rejects '+JSON.stringify(changes),()=>{const s=setup();assert.equal(post(s,changes).ok,false);assert.equal(s.table.length,2);});
test('adult guardian required and formula values escaped',()=>{const s=setup();assert.equal(post(s,{age:'18',nom:'=IMPORTXML("x")',pack:'1500'}).ok,true);assert.ok(s.table[2][s.table[0].indexOf('Nom')].startsWith("'="));});
test('duplicate committees rejected before writes',()=>{const s=setup();assert.equal(post(s,{comite_choix_1:'A',comite_choix_2:'A'}).code,'DUPLICATE_COMMITTEE_CHOICES');assert.equal(s.table.length,2);});
const {onRequestPost}=await import('../registration-site/functions/api/registration.js');
test('relay reads confirmation and follows Apps Script redirect',async()=>{const original=globalThis.fetch;globalThis.fetch=async(url,options)=>{assert.equal(url,'https://script.google.com/macros/s/test/exec');assert.equal(options.redirect,'follow');return Response.json({ok:true});};try{const result=await onRequestPost({request:new Request('https://example.com/api/registration',{method:'POST',body:new URLSearchParams(data)}),env:{APPS_SCRIPT_URL:'https://script.google.com/macros/s/test/exec'}});assert.deepEqual(await result.json(),{ok:true});}finally{globalThis.fetch=original;}});
test('relay refuses invalid configuration',async()=>{const r=await onRequestPost({request:new Request('https://example.com/api/registration',{method:'POST'}),env:{}});assert.equal(r.status,503);});

test('three confirmed choices and all four confirmations are stored',()=>{const s=setup();assert.equal(post(s).ok,true);const row=s.table[2];for(const field of ['Pack assumé','Code de conduite accepté','Informations exactes','Consentement'])assert.equal(row[s.table[0].indexOf(field)],'on');assert.equal(row[s.table[0].indexOf('Nombre de participations MUN')],'0');assert.equal(row[s.table[0].indexOf('Logistique et besoins particuliers')],'None');assert.equal(row.at(-1),data.motivation);});
test('contact parent remains required at age 25',()=>{const s=setup();assert.equal(post(s,{age:'25',contact_parent:''}).ok,false);});
for(const count of ['0','4','5','8'])test('participation count '+count+' is accepted',()=>assert.equal(post(setup(),{participations_mun:count}).ok,true));
